matrix:
  include:
     - language: c
       sudo: false # only for faster builds
       compiler: 
         - clang
         - gcc
       script:
         - gcc -o calc_function calc_function.c 
         - ./calc_function
